/* BankSathi: intentionally small and explainable NLP engine (no external API). */
const state = { entries: [], chat: [] };
const synonyms = {
  account:['account','khata','zero balance','saving','savings'], loan:['loan','credit','udhaar','borrow','emi'],
  business:['business','shop','dukkan','startup','entrepreneur','vyapar'], insurance:['insurance','bima','cover','accident','life'],
  pension:['pension','retirement','old age'], farmer:['farmer','kisan','agriculture','crop'], student:['student','college','study','education'],
  fraud:['fraud','scam','otp','upi','cyber','hack'], deposit:['fd','fixed deposit','rd','deposit','safe'], girl:['girl','daughter','beti']
};
const needs = {saving:['pmjdy','fd','rd','ppf','sukanya'],insurance:['pmsby','pmjjby'],pension:['apy','nps','ppf'],business:['mudra','standup'],education:['education'],farmer:['kcc']};

function normalise(text){ return text.toLowerCase().replace(/[^a-z0-9₹ ]/g,' ').replace(/\s+/g,' ').trim(); }
function words(text){ return normalise(text).split(' ').filter(Boolean); }
function expandedTerms(text){ const raw=normalise(text), terms=new Set(words(raw)); Object.entries(synonyms).forEach(([group,items])=>{if(items.some(x=>raw.includes(x))) {terms.add(group); items.forEach(x=>terms.add(x));}}); return terms; }
function intent(text){ const t=normalise(text); if(/fraud|scam|otp|upi|hack|unauthori[sz]ed/.test(t))return 'safety'; if(/emi|monthly payment|calculate/.test(t))return 'emi'; if(/eligible|recommend|which scheme|find scheme|best for/.test(t))return 'recommend'; if(/hello|hi |namaste|hey/.test(t))return 'greet'; return 'knowledge'; }
function ranked(text, limit=3){ const terms=expandedTerms(text); return state.entries.map(entry=>{const hay=[entry.name,entry.category,...entry.tags,entry.summary,entry.eligibility].join(' ').toLowerCase(); let score=0; terms.forEach(term=>{if(term.length>1 && hay.includes(term))score+= term.includes(' ')?3:1;}); return {...entry,score};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit); }
function money(n){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n)}
function card(x){return `<article class="result"><span class="badge">${x.category}</span><h3>${x.name}</h3><p>${x.summary}</p><p><b>Who can consider it:</b> ${x.eligibility}</p><a href="${x.source}" target="_blank" rel="noopener">Verify at official source ↗</a></article>`}
function reply(text){ const found=ranked(text), type=intent(text); if(type==='greet')return `<strong>Namaste!</strong><p>Tell me your goal—saving, loan, business, pension, insurance, education or a banking complaint—and I’ll point you to relevant options.</p>`; if(type==='safety')return `<strong>Act quickly to protect your account.</strong><p>Do not share OTP, PIN, CVV, passwords or approve unknown collect requests. Contact your bank through its official number/app immediately, then report the incident through the official cybercrime portal. For unresolved bank service complaints, first complain to the bank and then check the RBI Ombudsman route.</p>${found.map(x=>`<p>• <a href="${x.source}" target="_blank">${x.name} ↗</a></p>`).join('')}`; if(type==='emi')return `<strong>Use the EMI Calculator tab</strong><p>It shows a transparent estimate. Compare total interest—not only the monthly EMI—and include processing fees and rate-reset risk before deciding.</p>`; if(type==='recommend')return `${found.length?`<strong>These are the closest matches I found.</strong><p>They are options to verify, not a guarantee of eligibility or approval.</p>${found.map(x=>`<p><b>${x.name}</b> — ${x.summary}<br><a href="${x.source}" target="_blank">Official source ↗</a></p>`).join('')}`:`<strong>I need a little more detail.</strong><p>What is your main goal (account, savings, loan, insurance, pension or business), your age, and whether you are a student, farmer, entrepreneur or new to banking?</p>`}`; if(found.length)return `<strong>${found[0].name}</strong><p>${found[0].summary}</p><p><b>Eligibility:</b> ${found[0].eligibility}</p><p><b>Key point:</b> ${found[0].benefits[0]}</p><p><a href="${found[0].source}" target="_blank" rel="noopener">Check the official ${found[0].authority} source ↗</a></p>${found.length>1?`<p>You may also compare: ${found.slice(1).map(x=>x.name).join(', ')}.</p>`:''}`; return `<strong>I don’t want to guess with your money.</strong><p>I can help with bank accounts, FD/RD, loans, government schemes, insurance, pension, investment basics, fraud safety and complaints. Please rephrase with your goal.</p>`; }
function addMessage(html,who='bot'){const a=document.createElement('article');a.className=who==='user'?'user':'bot';a.innerHTML=who==='user'?`<div class="bubble">${html}</div>`:`<div class="avatar">₹</div><div class="bubble">${html}</div>`;document.querySelector('#conversation').append(a);a.scrollIntoView({behavior:'smooth',block:'end'});}
function runEMI(){const f=new FormData(document.querySelector('#emiForm')),P=Number(f.get('amount')),r=Number(f.get('rate'))/1200,n=Number(f.get('years'))*12;const emi=r===0?P/n:P*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1),total=emi*n;document.querySelector('#emi').textContent=money(emi);document.querySelector('#total').textContent=money(total);document.querySelector('#interest').textContent=money(total-P)}
async function init(){const response=await fetch('data/banking-knowledge.json');const db=await response.json();state.entries=db.entries;document.querySelector('#conversation').append(document.querySelector('#welcome').content.cloneNode(true));document.querySelector('#chatForm').addEventListener('submit',e=>{e.preventDefault();const q=document.querySelector('#question');if(!q.value.trim())return;addMessage(q.value,'user');addMessage(reply(q.value));q.value=''});document.querySelectorAll('.chips button').forEach(b=>b.addEventListener('click',()=>{addMessage(b.textContent,'user');addMessage(reply(b.textContent));}));document.querySelector('#clearChat').onclick=()=>{document.querySelector('#conversation').innerHTML='';document.querySelector('#conversation').append(document.querySelector('#welcome').content.cloneNode(true));};document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.panel').forEach(x=>x.classList.add('hidden'));document.querySelector('#'+b.dataset.view).classList.remove('hidden')});document.querySelector('#finderForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),need=f.get('need'),age=Number(f.get('age')),profile=f.get('profile');let picks=needs[need].map(id=>state.entries.find(x=>x.id===id));if(profile==='woman'&&need==='business')picks.unshift(state.entries.find(x=>x.id==='standup'));if(profile==='unbanked')picks.unshift(state.entries.find(x=>x.id==='pmjdy'));if(age&&need==='pension'&&age>40)picks=picks.filter(x=>x.id!=='apy');document.querySelector('#results').innerHTML=`<p class="result-note">Shortlisted from your stated need. Your bank/authority decides eligibility and approval.</p>${[...new Map(picks.filter(Boolean).map(x=>[x.id,x])).values()].map(card).join('')}`});document.querySelector('#emiForm').addEventListener('submit',e=>{e.preventDefault();runEMI()});runEMI();}
init().catch(()=>addMessage('<strong>Knowledge base could not load.</strong><p>Please serve this folder using a local web server, then refresh.</p>'));
